### ISSUE TITLE
Feature: Speed-catch / speed run / fast-catch

### ISSUE THREAD

**Issue by jxsl13** [Teelevision/zcatch#6]
If a player catches someone, a countdown starts counting down,  for how many minutes is set in the config.
If the player doesn't win the round within that countdown, he get's killed by the server.
Maybe with a server message or whatever

**Comment by Teelevision** [comment]
I actually thought of it a time ago. The reason I didn't do it was, if I remember correctly, that it would stretch long rounds even longer and would not affect short rounds. The benefit would be that noone has to wait very long when caught.
I'm as now undecided whether to add this or not. Maybe you could explain what you see in this idea of yours.

**Comment by Teelevision** [comment]
Sry, I didn't want to close this.^^

**Comment by gurk3nk3rn** [comment]
how about instead of adding a timer to end the round, add one for the next kill.

e.g. you kill someone. timer starts. you kill someone within that timer -> timer resets.
if you cant kill someone, half the players you caught get released

**Comment by Teelevision** [comment]
That sounds like a cool idea. Thanks.

**Comment by Teelevision** [comment]
Closed. I will implement both timer ideas as part of the hard mode (#13).
