### ISSUE TITLE
Release game feature request

### ISSUE THREAD

**Issue by jxsl13** [Teelevision/zcatch#7]
Simple: Due to the 5 players restriction lots of players release their caught opponents when there aren't enough players in order to win a round.
Adding a vote option to automatically release caught players while the server has less than 5 (or however players are set in the config) to win a round.

**Comment by Teelevision** [comment]
So basically an option for having colored iDM before the threshold for last standing (normal zCatch) is reached.
I could imagine it, but I am not convinced that it improves the game. The game should stay zCatch, which this change would not be. Maybe you could give me more input on the idea.

**Comment by Teelevision** [comment]
I won't implement this feature for now.
